version: '3.8'

services:
  # Prometheus - self monitoring
  prometheus-server-self-monitoring:
    image: prom/prometheus:v2.29.2
    volumes:
      - ./prometheus-server/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheusserver_self-monitoring_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9099:9090
    networks:
      - observabilitysandbox
    restart: always
    labels:
      org.label-schema.group: "observability"

volumes:
  prometheusserver_self-monitoring_data: {}

networks:
  observabilitysandbox:
    name: observabilitysandbox
    external: true
