version: '3.8'

services:
  # Prometheus + sidecar - cluster-02 - r2
  prometheus-server-cluster-02-r2:
    image: prom/prometheus:v2.29.2
    volumes:
      - ./prometheus-server/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheusserver_cluster02_r2_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.max-block-duration=30m'
      - '--storage.tsdb.min-block-duration=30m'
      - '--web.enable-lifecycle'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9093:9090
    networks:
      - observabilitysandbox
    restart: always
    labels:
      org.label-schema.group: "observability"

  thanos-sidecar-prometheus-cluster-02-r2:
    image: quay.io/thanos/thanos:v0.21.1
    volumes:
      - ./thanos/:/etc/thanos/
      - prometheusserver_cluster02_r2_data:/prometheus
    command:
      - 'sidecar'
      - '--tsdb.path=/prometheus'
      - '--prometheus.url=http://prometheus-server-cluster-02-r2:9090'
      - '--grpc-address=0.0.0.0:10091'
      - '--http-address=0.0.0.0:10902'
      - '--objstore.config-file=/etc/thanos/bucket_config.yaml'
    depends_on:
      - prometheus-server-cluster-02-r2
    networks:
      - observabilitysandbox
    restart: always
    labels:
      org.label-schema.group: "observability"

volumes:
  prometheusserver_cluster02_r2_data: {}

networks:
  observabilitysandbox:
    name: observabilitysandbox
    external: true
